default_install_hook_types: [pre-commit, pre-push]
repos:
  # General
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=250]
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer
      - id: sort-simple-yaml
        files: ^src/house_price_pred_ml/utils/tree.yaml$
      - id: trailing-whitespace

  # Secrets scanner
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks

  # Python linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  # Shell script linter
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck

  # Dockerfile linter
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1
    hooks:
      - id: hadolint

  # Markdown linter
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2

  # Local
  - repo: local
    hooks:
      # JSON, YAML, and Markdown formatter
      - id: pretty-format
        name: pretty format
        description: sets a standard for formatting json, yaml, and markdown files.
        entry: npx prettier --write
        language: node
        types_or: [json, yaml, markdown]

      # Check branch name format
      - id: check-branch
        name: check branch
        description: check branch name format before push.
        entry: ./bin/check-branch
        language: script
        stages: [pre-push]
        always_run: true
